<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/composer/autoload_real.php';
require_once __DIR__ . '\box\spout\src\Spout\Autoloader\Psr4Autoloader.php';

$loader = new Box\Spout\Autoloader\Psr4Autoloader();
$loader->register();
$loader->addNamespace('Box\Spout', 'vendor/box/spout/src/Spout');

return ComposerAutoloaderInit3ddf776627a64c859885cffe9f11b897::getLoader();
