
version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 80:80

  # The Database
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
      - "MYSQL_DATABASE=telkom"
      - "MYSQL_USER=telkom"
      - "MYSQL_PASSWORD=asdf1234"
      - "MYSQL_ROOT_PASSWORD=asdf1234"
    ports:
        - "33061:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - database
    ports:
      - 8181:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER=telkom
      - PMA_PASSWORD=asdf1234
      - PMA_HOST=database
      - PMA_PORT=3306

volumes:
  dbdata:
